<a href="https://colab.research.google.com/github/SanjanaPushpita/ANN-steps-math/blob/main/ANN_step_by_step.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Initialize input X, weights wh, biases bh, output weights wout, and output bias bout
# Input X
X = np.array([
    [1, 1, 0, 0],
    [0, 1, 0, 1],
    [1, 0, 1, 0]
])

# Target Output Y
Y = np.array([1, 1, 1])

# Weights and Biases
wh = np.array([
    [0.42, 0.32, 0.22],
    [0.11, 0.22, 0.52],
    [0.98, 0.62, 0.77],
    [0.88, 0.18, 0.60]
])

bh = np.array([0.56, 0.88, 0.07])

wout = np.array([0.40, 0.73, 0.52])
bout = 0.72


# Define activation function (Sigmoid) and Sigmoid derivative

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    return x * (1 - x)

# Forward Propagation

In [4]:
# Hidden layer input
hidden_layer_input = np.dot(X, wh) + bh

# Hidden layer activations
hidden_layer_activations = sigmoid(hidden_layer_input)

# Output layer input
output_layer_input = np.dot(hidden_layer_activations, wout) + bout

# Output layer activation (final output)
output = sigmoid(output_layer_input)


# Calculate Error

In [5]:
# Error
error = Y - output


In [6]:
print("Hidden Layer Input:\n", hidden_layer_input)
print("\nHidden Layer Activations:\n", hidden_layer_activations)
print("\nOutput Layer Input:\n", output_layer_input)
print("\nOutput:\n", output)
print("\nError:\n", error)

Hidden Layer Input:
 [[1.09 1.42 0.81]
 [1.55 1.28 1.19]
 [1.96 1.82 1.06]]

Hidden Layer Activations:
 [[0.74838172 0.80533842 0.6921095 ]
 [0.82491373 0.78244978 0.76674106]
 [0.87653295 0.86056613 0.74269055]]

Output Layer Input:
 [1.96714667 2.01985918 2.08502554]

Output:
 [0.87730431 0.88286645 0.8894392 ]

Error:
 [0.12269569 0.11713355 0.1105608 ]


# Backpropagation

In [7]:
lr = 0.1

In [8]:
slope_output_layer = sigmoid_derivative(output)
delta_output = error * slope_output_layer *lr

error_at_hidden_layer = delta_output[:, np.newaxis] * wout #This reshapes delta_output from shape (3,) to shape (3,1).
slope_hidden_layer = sigmoid_derivative(hidden_layer_activations)
delta_hidden_layer = error_at_hidden_layer * slope_hidden_layer

In [9]:
print("Slope Output Layer:\n", slope_output_layer)
print("\nDelta Output:\n", delta_output)
print("\nError at Hidden Layer:\n", error_at_hidden_layer)
print("\nSlope Hidden Layer:\n", slope_hidden_layer)

Slope Output Layer:
 [0.10764146 0.10341328 0.09833711]

Delta Output:
 [0.00132071 0.00121132 0.00108722]

Error at Hidden Layer:
 [[0.00052829 0.00096412 0.00068677]
 [0.00048453 0.00088426 0.00062988]
 [0.00043489 0.00079367 0.00056536]]

Slope Hidden Layer:
 [[0.18830652 0.15676845 0.21309394]
 [0.14443107 0.17022212 0.1788492 ]
 [0.10822294 0.11999207 0.1911013 ]]


## Update Output layer weights and biases

In [10]:
# Learning rate

wout += hidden_layer_activations.T.dot(delta_output) * lr
bout += np.sum(delta_output) * lr

In [22]:
print("\nUpdated wout:\n", wout)
print("\nUpdated bout:\n", bout)


Updated wout:
 [0.40029406 0.7302947  0.52026503]

Updated bout:
 0.7203619253848159


## Update Hidden layer weights and biases

In [23]:
# Update Hidden layer weights and biases
wh += X.T.dot(delta_hidden_layer) * lr
bh += np.sum(delta_hidden_layer, axis=1) * lr

In [24]:
print("\nUpdated wh:\n", wh)
print("\nUpdated bh:\n", bh)


Updated wh:
 [[0.41991299 0.31982405 0.22000697]
 [0.10995351 0.21991081 0.51999633]
 [0.97991817 0.61988155 0.7699964 ]
 [0.87995869 0.17996831 0.59998576]]

Updated bh:
 [0.55994789 0.87991276 0.06979613]
