In [ ]:
import numpy as np

In [ ]:
#Initialize input X, weights wh, biases bh, output weights wout, and output bias bout
# Input X
X = np.array([
    [1, 0, 1, 0],
    [1, 0, 1, 1],
    [0, 1, 0, 1]
])

# Target Output Y
Y = np.array([1, 1, 0])

# Weights and Biases
wh = np.array([
    [0.42, 0.88, 0.55],
    [0.10, 0.73, 0.68],
    [0.60, 0.18, 0.47],
    [0.92, 0.11, 0.52]
])

bh = np.array([0.46, 0.72, 0.08])

wout = np.array([0.30, 0.25, 0.23])
bout = 0.69


# Define activation function (Sigmoid) and Sigmoid derivative

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    return x * (1 - x)

# Forward Propagation

In [ ]:
# Hidden layer input
hidden_layer_input = np.dot(X, wh) + bh

# Hidden layer activations
hidden_layer_activations = sigmoid(hidden_layer_input)

# Output layer input
output_layer_input = np.dot(hidden_layer_activations, wout) + bout

# Output layer activation (final output)
output = sigmoid(output_layer_input)


# Calculate Error

In [ ]:
# Error
error = Y - output


In [ ]:
print("Hidden Layer Input:\n", hidden_layer_input)
print("\nHidden Layer Activations:\n", hidden_layer_activations)
print("\nOutput Layer Input:\n", output_layer_input)
print("\nOutput:\n", output)
print("\nError:\n", error)

Hidden Layer Input:
 [[1.48 1.78 1.1 ]
 [2.4  1.89 1.62]
 [1.48 1.56 1.28]]

Hidden Layer Activations:
 [[0.81457258 0.85569687 0.75026011]
 [0.9168273  0.86875553 0.83479513]
 [0.81457258 0.82635335 0.78244978]]

Output Layer Input:
 [1.32085581 1.37423995 1.32092356]

Output:
 [0.78932406 0.79806432 0.78933532]

Error:
 [ 0.21067594  0.20193568 -0.78933532]


# Backpropagation

In [ ]:
slope_output_layer = sigmoid_derivative(output)
delta_output = error * slope_output_layer

error_at_hidden_layer = delta_output[:, np.newaxis] * wout
slope_hidden_layer = sigmoid_derivative(hidden_layer_activations)
delta_hidden_layer = error_at_hidden_layer * slope_hidden_layer

## Update Output layer weights and biases

In [ ]:
# Learning rate
lr = 0.1
wout += hidden_layer_activations.T.dot(delta_output) * lr
bout += np.sum(delta_output) * lr

## Update Hidden layer weights and biases

In [ ]:
# Update Hidden layer weights and biases
wh += X.T.dot(delta_hidden_layer) * lr
bh += np.sum(delta_hidden_layer, axis=0) * lr

In [ ]:
# Print updated weights and biases
print("\nUpdated wh:\n", wh)
print("\nUpdated bh:\n", bh)
print("\nUpdated wout:\n", wout)
print("\nUpdated bout:\n", bout)


Updated wh:
 [[0.4202332  0.88020091 0.55025421]
 [0.09940524 0.72952915 0.67948612]
 [0.6002332  0.18020091 0.47025421]
 [0.91947969 0.10962191 0.51958935]]

Updated bh:
 [0.45963844 0.71973006 0.07974033]

Updated wout:
 [0.29514577 0.24497878 0.22507513]

Updated bout:
 0.6836322439645574
